# Video Editing Custom Nodes for ComfyUI
# 视频编辑自定义节点

from .edit_video import NODE_CLASS_MAPPINGS as EDIT_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS as EDIT_DISPLAY_MAPPINGS
from .mearge_video import NODE_CLASS_MAPPINGS as MERGE_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS as MERGE_DISPLAY_MAPPINGS

# 合并所有节点映射
NODE_CLASS_MAPPINGS = {**EDIT_MAPPINGS, **MERGE_MAPPINGS}
NODE_DISPLAY_NAME_MAPPINGS = {**EDIT_DISPLAY_MAPPINGS, **MERGE_DISPLAY_MAPPINGS}

# 导出节点映射和web目录
__all__ = ['NODE_CLASS_MAPPINGS', 'NODE_DISPLAY_NAME_MAPPINGS']
